# Site settings
title: Granite
tag_text:
description: Granite is a company that is redefineing trust on the blockchian

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
