# Site settings
title: Granite, The Trust Company
tag_text: Granite
description: Granite is a company that is redefineing trust on the blockchian

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
